..

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: NestJS CI Pipeline
+name: NestJS CI/CD Pipeline
 
 on:
   push:
@@ -13,7 +13,6 @@ jobs:
   build-and-test:
     name: Build and Run Tests
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -35,16 +34,21 @@ jobs:
 
       - name: Build Project
         run: npm run build
+
   deploy:
     name: Deploy to Back4App
     needs: build-and-test
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
 
       - name: Install Back4App CLI
-        run: curl -L https://github.com/back4app/b4a-cli/releases/latest/download/b4a_linux_amd64 -o b4a && chmod +x b4a
+        run: |
+          curl -L https://github.com/back4app/b4a-cli/releases/download/v0.1.2/b4a_linux_amd64 -o b4a
+          chmod +x b4a
+          if grep -q "Not Found" b4a; then echo "Download Failed"; exit 1; fi
 
       - name: Configure and Deploy
         env:
